site_name: SDKD
repo_url: https://github.com/glitch003/react-native-distributed-dev-kit
repo_name: 'GitHub'
edit_uri: ''
pages:
  - Home: index.md
  - Modules: 
    - 'Overview': 'modules/index.md'
    - 'Wallet': 'modules/wallet.md'
